name: SilkTouchHands
version: ${project.version}
description: Harness the power of the enderman inside of you
author: visualcody
website: https://github.com/visual-cody
main: com.visualcody.silktouchhands.main
api-version: 1.16

permissions:xxXOni GenjiXxx
  silktouchhands.silktouch:
    default: op
    description: Allows a player to silktouch blocks with their bare hands
  siltouchhands.*: true
    default: op
    children:
      silktouchhands.silktouch: true
